// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5FEgaZIP18Bets2Ab07b0yQFVaQqlutA',
    appId: '1:1044551899476:web:24bd41111e312ebf42d0c1',
    messagingSenderId: '1044551899476',
    projectId: 'jobfinder-d7188',
    authDomain: 'jobfinder-d7188.firebaseapp.com',
    storageBucket: 'jobfinder-d7188.appspot.com',
    measurementId: 'G-7PVFHKRXJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWAsazWEkcCdYPerNiN0mVF1ciEONU6EU',
    appId: '1:1044551899476:android:31a63787fc2ee36942d0c1',
    messagingSenderId: '1044551899476',
    projectId: 'jobfinder-d7188',
    storageBucket: 'jobfinder-d7188.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVV1YsVn8ClGqYaBoA_bxdHc_ZY8lG5aI',
    appId: '1:1044551899476:ios:98f0f0c409b02a1842d0c1',
    messagingSenderId: '1044551899476',
    projectId: 'jobfinder-d7188',
    storageBucket: 'jobfinder-d7188.appspot.com',
    iosBundleId: 'com.example.jobfinderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVV1YsVn8ClGqYaBoA_bxdHc_ZY8lG5aI',
    appId: '1:1044551899476:ios:43fc66bc24e0cd7e42d0c1',
    messagingSenderId: '1044551899476',
    projectId: 'jobfinder-d7188',
    storageBucket: 'jobfinder-d7188.appspot.com',
    iosBundleId: 'com.example.jobfinderApp.RunnerTests',
  );
}
